INSERT INTO Departments
VALUES
('BAN', 'Department of Bangla'),
('ENG', 'Department of English'),
('HIS', 'Department of History'),
('PHI', 'Department of Philosophy'),
('IHC', 'Department of Islamic History and Culture'),
('ARA', 'Department of Arabic'),
('ISLSTU', 'Department of Islamic Studies'),
('DRA', 'Department of Dramatics'),
('IML', 'Institute of Modern Languages'),
('FINART', 'Department of Fine Arts'),
('PLL', 'Department of Persian Language and Literature'),
('PAL', 'Department of Pali'),
('SAN', 'Department of Sanskrit'),
('IER', 'Institute of Education and Research'),
('MUS', 'Department of Music'),
('BANSTU', 'Department of Bangladesh Studies'),
('PHY', 'Department of Physics'),
('CHE', 'Department of Chemistry'),
('MAT', 'Department of Mathematics'),
('STA', 'Department of Statistics'),
('ACCE', 'Department of Applied Chemistry and Chemical Engineering'),
('IFES', 'Institute of Forestry and Environmental Science'),
('ACC', 'Department of Accounting'),
('MAN', 'Department of Management'),
('FIN', 'Department of Finance'),
('MAR', 'Department of Marketing'),
('HRM', 'Department of Human Resource Management'),
('BANINS', 'Department of Banking and Insurance'),
('ECO', 'Department of Economics'),
('POLSCI', 'Department of Political Science'),
('SOC', 'Department of Sociology'),
('PUBADM', 'Department of Public Administration'),
('ANT', 'Department of Anthropology'),
('INTREL', 'Department of International Relations'),
('COMJOU', 'Department of Communication and Journalism'),
('CPS', 'Department of Criminology and Police Science'),
('DEVSTU', 'Department of Development Studies'),
('LAW', 'Department of Law'),
('BOT', 'Department of Botany'),
('ZOO', 'Department of Zoology'),
('GES', 'Department of Geography and Environmental Studies'),
('BMB', 'Department of Biochemistry and Molecular Biology'),
('MIC', 'Department of Microbiology'),
('SOISCI', 'Department of Soil Science'),
('GEB', 'Department of Genetic Engineering and Biotechnology'),
('PSY', 'Department of Psychology'),
('PHA', 'Department of Pharmacy'),
('CSE', 'Department of Computer Science and Engineering'),
('EEE', 'Department of Electrical and Electronic Engineering'),
('PESS', 'Department of Physical Education and Sports Science'),
('IMS', 'Institute of Marine Sciences'),
('OCE', 'Department of Oceanography'),
('FIS', 'Department of Fisheries'),
('PED', 'Department of Pediatrics'),
('ICO', 'Institute of Community Ophthalmology');

INSERT INTO Course
VALUES
('CSE-413', 'Database Management System', 4, 'CSE'),
('CSE-414', 'Database Management System Lab', 4, 'CSE'),
('CSE-415', 'Microprocessors', 4, 'CSE'),
('CSE-416', 'Microprocessors Lab', 4, 'CSE'),
('CSE-411', 'Design and Analysis of Algorithms', 4, 'CSE'),
('CSE-412', 'Design and Analysis of Algorithms Lab', 4, 'CSE'),
('MAT-431', 'Numerical Methods', 4, 'CSE'),
('MAT-432', 'Numerical Methods Lab', 4, 'CSE');

SELECT *
FROM Thana
WHERE district LIKE 'Dhaka%'
LIMIT 5;